ALTER TYPE "WorkSurface" ADD VALUE IF NOT EXISTS 'ENTRY_WALL';
ALTER TYPE "WorkSurface" ADD VALUE IF NOT EXISTS 'FRONT_WALL';
ALTER TYPE "WorkSurface" ADD VALUE IF NOT EXISTS 'RIGHT_WALL';
ALTER TYPE "WorkSurface" ADD VALUE IF NOT EXISTS 'LEFT_WALL';
